spring:
  profiles:
    active: "@activatedProperties@"
  devtools:
    livereload:
      # 热部署端口，不要和运行的端口重复即可
      port: 9090
  servlet:
    multipart:
      # 单文件大小限制
      max-file-size: 10MB
      # 总文件大小限制
      max-request-size: 10MB

jwt:
  config:
    secret_key: "C*F-JaNdRgUkXn2r5u8x/A?D(G+KbPeShVmYq3s6v9y$B&E)H@McQfTjWnZr4u7w"
